import {
  boolock,
  dongnaebangnae,
  inhachoi,
  mdn,
  react,
  refreigerator,
} from "@/shared/assets";

export const PROJECTS = [
  {
    src: inhachoi,
    alt: "개발자 최경일 프로젝트 썸네일 사진",
    title: "개발자 최경일",
    description: "개인 홈페이지 1인 프로젝트!",
    period: "25.11 ~ ",
    url: "https://github.com/inhachoi/inha-choi",
  },
  {
    src: boolock,
    alt: "BooLock 프로젝트 썸네일 사진",
    title: "BooLock",
    description: "HTML과 CSS를 블록으로 쉽게 익히는 블록코딩 플랫폼!",
    period: "24.10 ~ 25.01",
    url: "https://github.com/boostcampwm-2024/refactor-web31-BooLock",
  },
  {
    src: dongnaebangnae,
    alt: "동네방네 프로젝트 썸네일 사진",
    title: "동네방네",
    description: "동네와 주민들에 대한 유대감을 증대시키주는 SNS!",
    period: "24.03 ~ 24.05",
    url: "https://github.com/Dongnaebangnae/FE",
  },
  {
    src: refreigerator,
    alt: "냉장고를 부탁해 프로젝트 썸네일 사진",
    title: "냉장고를 부탁해",
    description:
      "탄소 배출량 및 전력 사용량 감소를 유도하는 친환경 스마트 냉장고!",
    period: "24.03 ~ 24.05",
    url: "https://velog.io/@chlruddlf73/Project-Advantech-AloT-Innoworks-Project-2024",
  },
];

export const OPEN_SOURCE_CONTRIBUTION = [
  {
    url: "https://github.com/reactjs/ko.react.dev/pull/1356#issuecomment-3567598733",
    src: react,
    content: "reactjs / ko.react.dev Effect 문서 번역",
    date: "2025.11",
  },
  {
    url: "https://github.com/reactjs/ko.react.dev/pull/1355",
    src: react,
    content: "reactjs / ko.react.dev 커스텀 훅 문서 번역",
    date: "2025.11",
  },
  {
    url: "ttps://github.com/mdn/translated-content/pull/28427",
    src: mdn,
    content: "mdn / translated-contenteact.dev 비동기 예시 코드 수정",
    date: "2025.08",
  },
];

export const FOOD_NAMES = [
  "대창 듬뿍 곱도리탕",
  "불향 솔솔 차돌짬뽕",
  "건강한 키토김밥",
  "남자의 소울푸드 돈까스",
  "촉촉한 치즈돈까스",
  "산더미 제육볶음",
  "한국인 소울푸드 삼겹살",
  "구수한 청국장",
  "두부 듬뿍 된장찌개",
  "진하게 우려낸 돼지국밥",
  "속 풀리는 얼큰 해장국",
  "든든한 소머리국밥",
  "고기 가득 소불고기덮밥",
  "BBQ 황금올리브 치킨",
  "매콤달달한 닭갈비",
  "교촌 허니콤보",
  "BHC 뿌링클",
  "칼칼한 묵은지 김치찌개",
  "든든한 뼈해장국",
  "담백한 잔치국수 한그릇",
  "새콤달콤 비빔국수",
  "햄듬뿍 부대찌개",
  "고소한 육개장 칼국수",
  "얼큰한 버섯전골",
  "뜨끈한 어묵우동",
  "신선한 육회비빔밥",
  "갈비향 물씬 갈비만두",
  "속이 꽉 찬 고기왕만두",
  "치즈 주욱~ 치즈떡볶이",
  "매콤달달 로제 엽떡",
  "마라향 가득 마라샹궈",
  "MZ 대표음식 마라탕",
  "탕수육에 짜장면",
  "고소한 까르보나라",
  "버섯향 진한 크림리조또",
  "고급진 수제버거",
  "버거킹 근본 와퍼",
  "롯데리아 새우버거",
  "우아하게 파스타",
  "맛없없 스팸마요덮밥",
  "바삭한 치킨마요덮밥",
  "시원한 냉모밀",
  "얼음 동동 물냉면",
  "매콤달달 비빔냉면",
  "참기름향 물씬 비빔밥",
  "근본 김밥+라면",
  "고기듬뿍 스테이크덮밥",
  "단짠 치킨데리야키덮밥",
  "촉촉한 오므라이스",
  "김볶밥밥 with 반숙후라이",
  "과일 듬뿍 요거트볼",
  "건강한 닭가슴살샐러드",
  "신선한 연어포케",
  "피자스쿨 고구마피자",
];
