/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as MainLayoutRouteImport } from './routes/_mainLayout'
import { Route as SplatRouteImport } from './routes/$'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as MainLayoutIndexRouteImport } from './routes/_mainLayout/index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as MainLayoutSlugRouteImport } from './routes/_mainLayout/$slug'

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PostsRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => GamesRoute,
} as any)
const MainLayoutSlugRoute = MainLayoutSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof MainLayoutIndexRoute
  '/chat': typeof ChatRoute
  '/games': typeof GamesRouteWithChildren
  '/guestbook': typeof GuestbookRoute
  '/posts': typeof PostsRouteWithChildren
  '/$slug': typeof MainLayoutSlugRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/chat': typeof ChatRoute
  '/guestbook': typeof GuestbookRoute
  '/posts': typeof PostsRouteWithChildren
  '/$slug': typeof MainLayoutSlugRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/': typeof MainLayoutIndexRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/chat': typeof ChatRoute
  '/games': typeof GamesRouteWithChildren
  '/guestbook': typeof GuestbookRoute
  '/posts': typeof PostsRouteWithChildren
  '/_mainLayout/$slug': typeof MainLayoutSlugRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/_mainLayout/': typeof MainLayoutIndexRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/chat'
    | '/games'
    | '/guestbook'
    | '/posts'
    | '/$slug'
    | '/games/$gameId'
    | '/posts/$slug'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/chat'
    | '/guestbook'
    | '/posts'
    | '/$slug'
    | '/games/$gameId'
    | '/posts/$slug'
    | '/'
    | '/games'
  id:
    | '__root__'
    | '/$'
    | '/_mainLayout'
    | '/chat'
    | '/games'
    | '/guestbook'
    | '/posts'
    | '/_mainLayout/$slug'
    | '/games/$gameId'
    | '/posts/$slug'
    | '/_mainLayout/'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  ChatRoute: typeof ChatRoute
  GamesRoute: typeof GamesRouteWithChildren
  GuestbookRoute: typeof GuestbookRoute
  PostsRoute: typeof PostsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof PostsRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/_mainLayout/$slug': {
      id: '/_mainLayout/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof MainLayoutSlugRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainLayoutSlugRoute: typeof MainLayoutSlugRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutSlugRoute: MainLayoutSlugRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

interface GamesRouteChildren {
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesGameIdRoute: GamesGameIdRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface PostsRouteChildren {
  PostsSlugRoute: typeof PostsSlugRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsSlugRoute: PostsSlugRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  MainLayoutRoute: MainLayoutRouteWithChildren,
  ChatRoute: ChatRoute,
  GamesRoute: GamesRouteWithChildren,
  GuestbookRoute: GuestbookRoute,
  PostsRoute: PostsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
